SHELL_CONFIG=$HOME/etc/zsh

source $SHELL_CONFIG/prezto/init.zsh
source $SHELL_CONFIG/alias-tips/alias-tips.plugin.zsh

bindkey -a u undo
bindkey -a '^R' redo

alias la='ls -a'

alias gs='git status'
